### ISSUE TITLE
These are not really issues but something useful for to work with.

### ISSUE THREAD

**Issue by ijunaid8989** [ijunaid8989/ever-deployed#1]
there are 2 ansible tasks such as

```
- name: Register evercam-media local commit hash
  local_action:
    shell
    chdir={{local_media_dir}}
    git log --pretty='{"sha":"%h", "authorName":"%an", "authorEmail":"%ae", "commiterName":"%cn", "commiterEmail":"%ce", "authorUnixTimestamp":"%at", "commiterUnixTimestamp":"%ct", "subject":"%s", "branch":"%d", "deployType":"hotcode"}' | head -1
  register: local_commit_info

- set_fact:
    commit: "{{ local_commit_info.stdout|from_json }}"

- uri: 
    url: "https://ever-deployed.herokuapp.com/v1/server/deployed"
    method: POST
    return_content: yes
    body_format: json
    body: "{{ commit }}"
    status_code: 201, 200
  register: result

```

Through which you can gather some nice information about your commits and then send it using URI module to `https://ever-deployed.herokuapp.com/v1/server/deployed`

And this is programmed to get the data and then push it towards MongoDb.

and then on nuxt side you can have some good information such as

http://ever-deployed.herokuapp.com

![image](https://user-images.githubusercontent.com/13561999/72055366-87c92b00-32ec-11ea-8d61-7fc9492d71cd.png)
